[package]
name = "rust_ci_github_actions_workflow"
version = "0.1.0"
authors = ["test@example.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
coverage = []

[dependencies]
